# Rust-analyzer configuration for better performance

# Check configuration
[check]
# Only check the current package, not the whole workspace
workspace = false
# Don't check all targets (tests, benches, examples)
allTargets = false

# Build script configuration
[cargo]
# Don't rebuild build scripts on every save
buildScripts.rebuildOnSave = false
# Only analyze current package dependencies
autoreload = true

# Diagnostics
[diagnostics]
# Disable experimental diagnostics that might slow things down
experimental.enable = false

# Proc macros
[procMacro]
# Keep proc macros enabled but optimize
enable = true
attributes.enable = true

# Cache configuration
[cachePriming]
# Enable cache priming for faster startup
enable = true
# Use default number of threads
numThreads = 0

# Completion settings
[completion]
# Keep auto-import but disable postfix completions
autoimport.enable = true
postfix.enable = false

# Inlay hints (disable for performance)
[inlayHints]
typeHints.enable = false
parameterHints.enable = false
chainingHints.enable = false

# Code lens (disable for performance)
[lens]
enable = false
run.enable = false
debug.enable = false
implementations.enable = false
references.enable = false
