[build]
# Use incremental compilation
incremental = true

# Speed up linking on macOS
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/ld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/ld"]

# Optional: Use faster linker (mold or lld if installed)
# Uncomment if you have mold installed: brew install mold
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# [target.aarch64-apple-darwin]  
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# Build optimizations
[profile.dev]
# Faster compilation at the cost of runtime performance
opt-level = 0
# Faster builds with less debug info
debug = 1
# Split debuginfo for faster linking on macOS
split-debuginfo = "unpacked"
# Incremental compilation
incremental = true
# Faster builds by not including debug info for dependencies
[profile.dev.package."*"]
opt-level = 0
debug = false

# Optional: Create a custom profile for quick iteration
[profile.quick]
inherits = "dev"
opt-level = 0
debug = 0
incremental = true
codegen-units = 256
lto = false
