# This is a **reuseable** workflow that bundles the Desktop App for macOS.
# It doesn't get triggered on its own. It gets used in multiple workflows:
#  - release.yml
#  - canary.yml
on:
  workflow_call:
    inputs:
      version:
        required: false
        default: ""
        type: string
      # Let's allow overriding the OSes and architectures in JSON array form:
      # e.g. '["ubuntu-latest","macos-latest"]'
      # If no input is provided, these defaults apply.
      operating-systems:
        type: string
        required: false
        default: '["ubuntu-latest","macos-latest","windows-latest"]'
      architectures:
        type: string
        required: false
        default: '["x86_64","aarch64"]'

name: "Reusable workflow to build CLI"

jobs:
  build-cli:
    name: Build CLI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.operating-systems) }}
        architecture: ${{ fromJson(inputs.architectures) }}
        include:
          - os: ubuntu-latest
            target-suffix: unknown-linux-gnu
          - os: macos-latest
            target-suffix: apple-darwin
          - os: windows-latest
            target-suffix: pc-windows-gnu
            architecture: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version in Cargo.toml
        if: ${{ inputs.version != '' }}
        run: |
          sed -i.bak 's/^version = ".*"/version = "'${{ inputs.version }}'"/' Cargo.toml
          rm -f Cargo.toml.bak

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.architecture }}-${{ matrix.target-suffix }}

      - name: Install cross
        if: runner.os != 'Windows'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build CLI
        if: runner.os != 'Windows'
        env:
          CROSS_NO_WARNINGS: 0
          RUST_LOG: debug
          RUST_BACKTRACE: 1
          CROSS_VERBOSE: 1
        run: |
          export TARGET="${{ matrix.architecture }}-${{ matrix.target-suffix }}"
          rustup target add "${TARGET}"
          echo "Building for target: ${TARGET}"
          echo "Rust toolchain info:"
          rustup show
          echo "Cross version:"
          cross --version

          # 'cross' is used to cross-compile for different architectures (see Cross.toml)
          cross build --release --target ${TARGET} -p goose-cli -vv

          # tar the goose binary as goose-<TARGET>.tar.bz2
          cd target/${TARGET}/release
          tar -cjf goose-${TARGET}.tar.bz2 goose
          echo "ARTIFACT=target/${TARGET}/release/goose-${TARGET}.tar.bz2" >> $GITHUB_ENV
        shell: bash

      - name: Build CLI (Windows)
        if: runner.os == 'Windows'
        run: |
          $TARGET="${{ matrix.architecture }}-${{ matrix.target-suffix }}"
          rustup target add $TARGET
          echo "Building for target: $TARGET"
          
          # Build the CLI
          cargo build --release --target $TARGET -p goose-cli
          
          # Install MinGW dependencies if needed
          choco install mingw --version=8.1.0
          
          # Create directory for packaging
          New-Item -ItemType Directory -Path "./target/$TARGET/release/package" -Force | Out-Null
          
          # Copy the CLI binary
          Copy-Item ./target/$TARGET/release/goose.exe ./target/$TARGET/release/package/
          
          # Copy MinGW DLLs - try both possible locations
          $mingwPaths = @(
            "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin",
            "C:\tools\mingw64\bin"
          )
          
          foreach ($path in $mingwPaths) {
            if (Test-Path "$path\libstdc++-6.dll") {
              Write-Host "Found MinGW DLLs in $path"
              Copy-Item "$path\libstdc++-6.dll" ./target/$TARGET/release/package/
              Copy-Item "$path\libgcc_s_seh-1.dll" ./target/$TARGET/release/package/
              Copy-Item "$path\libwinpthread-1.dll" ./target/$TARGET/release/package/
              break
            }
          }
          
          # Copy any other DLLs from the release directory
          Get-ChildItem ./target/$TARGET/release/*.dll | ForEach-Object {
            Copy-Item $_ ./target/$TARGET/release/package/
          }
          
          # Create ZIP archive
          Compress-Archive -Path ./target/$TARGET/release/package/* -DestinationPath ./target/$TARGET/release/goose-$TARGET.zip
          
          echo "ARTIFACT=target/$TARGET/release/goose-$TARGET.zip" | Out-File -Append -FilePath $env:GITHUB_ENV
        shell: pwsh

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: goose-${{ matrix.architecture }}-${{ matrix.target-suffix }}
          path: ${{ env.ARTIFACT }}
