# This is a **reuseable** workflow that bundles the Desktop App for macOS.
# It doesn't get triggered on its own. It gets used in multiple workflows:
#  - release.yml
#  - canary.yml
#  - pr-comment-bundle-desktop.yml
on:
  workflow_call:
    inputs:
      version:
        description: 'Version to set for the build'
        required: false
        default: ""
        type: string
      signing:
        description: 'Whether to perform signing and notarization'
        required: false
        default: false
        type: boolean
      quick_test:
        description: 'Whether to perform the quick launch test'
        required: false
        default: true
        type: boolean
      ref:
        description: 'Git ref to checkout (branch, tag, or SHA)'
        required: false
        type: string
      pr_number:
        description: 'PR number to fetch'
        required: false
        type: string
    secrets:
      CERTIFICATE_OSX_APPLICATION:
        description: 'Certificate for macOS application signing'
        required: false
      CERTIFICATE_PASSWORD:
        description: 'Password for the macOS certificate'
        required: false
      APPLE_ID:
        description: 'Apple ID for notarization'
        required: false
      APPLE_ID_PASSWORD:
        description: 'Password for the Apple ID'
        required: false
      APPLE_TEAM_ID:
        description: 'Apple Team ID'
        required: false

name: Reusable workflow to bundle desktop app

jobs:
  bundle-desktop:
    runs-on: macos-latest
    name: Bundle Desktop App on macOS
    steps:
      # Debug information about the workflow and inputs
      - name: Debug workflow info
        run: |
          echo "Workflow source info:"
          echo "  Workflow file: ${{ github.workflow }}"
          echo "  Workflow ref: ${{ github.ref }}"
          echo "  Event name: ${{ github.event_name }}"
          echo "  Repository: ${{ github.repository }}"
          echo ""
          echo "Input parameters:"
          echo "  Requested ref: ${{ inputs.ref }}"
          echo "  PR number: ${{ inputs.pr_number }}"
          echo "  Version: ${{ inputs.version }}"
          echo "  Signing enabled: ${{ inputs.signing }}"
          echo "  Quick test enabled: ${{ inputs.quick_test }}"

      # Check initial disk space
      - name: Check initial disk space
        run: df -h

      # Validate Signing Secrets if signing is enabled
      - name: Validate Signing Secrets
        if: ${{ inputs.signing }}
        run: |
          if [[ -z "${{ secrets.CERTIFICATE_OSX_APPLICATION }}" ]]; then
            echo "Error: CERTIFICATE_OSX_APPLICATION secret is required for signing."
            exit 1
          fi
          if [[ -z "${{ secrets.CERTIFICATE_PASSWORD }}" ]]; then
            echo "Error: CERTIFICATE_PASSWORD secret is required for signing."
            exit 1
          fi
          if [[ -z "${{ secrets.APPLE_ID }}" ]]; then
            echo "Error: APPLE_ID secret is required for signing."
            exit 1
          fi
          if [[ -z "${{ secrets.APPLE_ID_PASSWORD }}" ]]; then
            echo "Error: APPLE_ID_PASSWORD secret is required for signing."
            exit 1
          fi
          if [[ -z "${{ secrets.APPLE_TEAM_ID }}" ]]; then
            echo "Error: APPLE_TEAM_ID secret is required for signing."
            exit 1
          fi
          echo "All required signing secrets are present."

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0  # Fetch all history
          submodules: recursive

      - name: Debug git status
        run: |
          echo "Git status after checkout:"
          git status
          echo ""
          echo "Current commit:"
          git rev-parse HEAD
          echo ""
          echo "Recent commits:"
          git log --oneline -n 5
          echo ""
          echo "Remote branches:"
          git branch -r

      # Rest of the workflow remains the same...