name: Smoke Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [anthropic, openai]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Hermit
        run: source ./bin/activate-hermit
      
      - name: Build Release Binary
        run: |
          source ./bin/activate-hermit
          cargo build --release
      
      - name: Run Smoke Test
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROVIDERS: ${{ matrix.provider }}
        run: ./tests/smoke/run_smoke_tests.sh
